export const LOADED = 'LOADED';
export const HEADERSCROLLED = 'HEADERSCROLLED';
export const ABOUTSCROLLED = 'ABOUTSCROLLED';
export const PROJECTSCROLLED = 'PROJECTSCROLLED';
export const EXPERIENCESCROLLED = 'EXPERIENCESCROLLED';
