import { useState, useEffect } from 'react';
import Head from 'next/head';
import Layout from '../components/Layout';
import Hero from '../components/sections/Hero';
import About from '../components/sections/About';
import Projects from '../components/sections/Projects';
import Experience from '../components/sections/Experience';

const HomePage = () => {
  const [loaded, setLoaded] = useState(false);
  const [headerScrolled, setHeaderScrolled] = useState(false);
  const [aboutScrolled, setAboutScrolled] = useState(false);
  const [projectsScrolled, setProjectsScrolled] = useState(false);
  const [experienceScrolled, setExperienceScrolled] = useState(false);

  useEffect(function mount() {
    function onLoad() {
      setTimeout(() => setLoaded(true), 3000);
    }

    window.addEventListener('load', onLoad);

    return function unMount() {
      window.removeEventListener('load', onLoad);
    };
  });

  useEffect(function mount() {
    function onScroll() {
      window.scrollY >= 200
        ? setHeaderScrolled(true)
        : setHeaderScrolled(false);
      window.scrollY >= 250 ? setAboutScrolled(true) : setAboutScrolled(false);
      window.scrollY >= 800
        ? setProjectsScrolled(true)
        : setProjectsScrolled(false);
      window.scrollY >= 1500
        ? setExperienceScrolled(true)
        : setExperienceScrolled(false);
    }

    window.addEventListener('scroll', onScroll);

    return function unMount() {
      window.removeEventListener('scroll', onScroll);
    };
  });

  return (
    <>
      <Head>
        <title>Elliot Hwang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout loaded={loaded} scrolled={headerScrolled}>
        <main>
          <Hero loaded={loaded} />
          {/* TODO: add styled corners around content sections */}
          <section id="about">
            <About scrolled={aboutScrolled} />
          </section>
          <section id="projects">
            <Projects scrolled={projectsScrolled} />
          </section>
          <section id="experience">
            <Experience scrolled={experienceScrolled} />
          </section>
        </main>
      </Layout>
    </>
  );
};

export default HomePage;
